### ISSUE TITLE
S5 - User story - add a column in the "history table", the type of request and with the corresponding color

### ISSUE THREAD

**Issue by angel5644** [angel5644/PerformanceEvaluation#187]
Detailed description

**Comment by dalvarado0** [comment]
Testing the user story with differents types of request.

**Comment by dalvarado0** [comment]
Report of the user story - "add a column in the "history table", the type of request and with the corresponding color"
[Issue #187.pdf](https://github.com/angel5644/PerformanceEvaluation/files/2435715/Issue.187.pdf)
