### ISSUE TITLE
Vacations - Research about the vacations process

### ISSUE THREAD

**Issue by angel5644** [angel5644/PerformanceEvaluation#34]
- Please do some research about this process
- A flow diagram/or any other diagram migh be required to represet this process

**Comment by Rair15** [comment]
![pes_vacations_flowchart](https://cloud.githubusercontent.com/assets/23217838/20017178/19e9efb8-a288-11e6-9b0c-ed4d94390ad9.png)

Vacations process diagram #34

**Comment by angel5644** [comment]
Excellent diagram!
