### ISSUE TITLE
Lateness Report - Mockups Sprint 1 

### ISSUE THREAD

**Issue by angel5644** [angel5644/PerformanceEvaluation#36]
- Please create the mockups of the changes of sprint 1

**Comment by angel5644** [comment]
Once you finish the mockups, please upload them to this thread.

**Comment by Felipelk** [comment]
![employee information](https://cloud.githubusercontent.com/assets/23040437/20017399/04ce55c8-a289-11e6-8c80-093a8c7ed883.JPG)
![lateness report vista 1](https://cloud.githubusercontent.com/assets/23040437/20017406/0b23dc86-a289-11e6-8129-de3795c6a4a8.jpg)

**Comment by angel5644** [comment]
Great!

@Felipelk, do you happen to have the mocks (image files) from Balsamick?

**Comment by Felipelk** [comment]
![lateness report mockup](https://cloud.githubusercontent.com/assets/23040437/20078187/3042fdac-a505-11e6-94bb-30cd7fde2665.png)

**Comment by angel5644** [comment]
We might need them for documentation.
