### ISSUE TITLE
Lateness Report  - DB changes Sprint 1

### ISSUE THREAD

**Issue by angel5644** [angel5644/PerformanceEvaluation#37]
- Please add to the DB the changes for Sprint 1. Upload/update the scritps in the project
- Create the corresponding diagrams for these changes

**Comment by IvanDenneb1** [comment]
![databaseupdatedmodel](https://cloud.githubusercontent.com/assets/19409131/20017213/40a506f6-a288-11e6-831e-1a6d61b41227.png)

**Comment by angel5644** [comment]
Cool!

**Comment by angel5644** [comment]
The only table added for this was the "Lateness" table, right @IvanDenneb1?

**Comment by IvanDenneb1** [comment]
Nope, we had to create more tables that were missing, such as "PERIOD" and "LOCATION" as well. 
And that's it

**Comment by angel5644** [comment]
Got it.
