### ISSUE TITLE
Vacations - Approach vacations changes

### ISSUE THREAD

**Issue by angel5644** [angel5644/PerformanceEvaluation#40]
- Lets create an approach of how to to handle the "Vacations" part of the project

   - What db changes (tables, fields) will be needed? 
   - What new screens?
   - Do we need to modify existing code/screens/db?
   - What resources are we going to need?
      - Excel files of the current vacations
      - Anything else?
   - What technologies are going to need?
      - Open air api
      - Anything else?

Based on all of these, we will define sprint 1 to start coding this part.

**Comment by Rair15** [comment]
Here some ideas I had... hope it helps

[2nd scope - ideas.txt](https://github.com/angel5644/PerformanceEvaluation/files/572755/2nd.scope.-.ideas.txt)

**Comment by angel5644** [comment]
Great ideas @Rair15. Thank you, we'll check them out.
